# Generated by Django 2.0.1 on 2018-04-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Haozx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNum', models.CharField(default='', max_length=255, verbose_name='手机号')),
                ('name', models.CharField(default='', max_length=255, verbose_name='姓名')),
                ('idCard', models.CharField(default='', max_length=255, verbose_name='身份证')),
                ('smsCode', models.CharField(default='', max_length=255, verbose_name='短信验证码')),
                ('smsSend', models.IntegerField(choices=[(0, '未发送'), (1, '已发送')], default=0, verbose_name='短信是否发送')),
                ('codeUsed', models.IntegerField(choices=[(0, '未使用'), (1, '已使用')], default=0, verbose_name='验证码是否已使用')),
                ('timestamp', models.CharField(default='', max_length=255, verbose_name='请求时间')),
                ('result', models.TextField(default='', verbose_name='查询结果')),
            ],
            options={
                'verbose_name': '好甄信',
                'verbose_name_plural': '好甄信',
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=255, verbose_name='Token')),
                ('timestamp', models.CharField(default='', max_length=255, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Token',
            },
        ),
    ]
